import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap/dist/js/bootstrap.min.js';
import './style/main.css';
import './icon/mylogo.png';
import './icon/mal.png';
import './icon/favicon.ico';
import './icon/favicon.png';
import '@fortawesome/fontawesome-free/js/fontawesome';
import '@fortawesome/fontawesome-free/js/solid';
import '@fortawesome/fontawesome-free/js/regular';
import '@fortawesome/fontawesome-free/js/brands';
import 'jquery/dist/jquery.min.js';
import './script/API/data.js'
import './script/main.js';
import './script/elements/result-content.js';